name: Release

on:
  push:
    branches:
      - master

permissions:
  contents: write
  discussions: write

jobs:
  build:
    strategy:
      matrix:
        include:
          # Linux
          - os: ubuntu-latest
            arch: x86_64
          - os: ubuntu-latest
            arch: aarch64
          # macOS
          - os: macos-latest
            arch: x86_64
          - os: macos-latest
            arch: arm64
          # FreeBSD
          - os: ubuntu-latest
            arch: x86_64
            freebsd: true

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        if: matrix.arch == 'aarch64'
        uses: docker/setup-qemu-action@v3

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux' && !matrix.freebsd
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc python3 python3-pip ninja-build zlib1g-dev
          sudo pip3 install meson

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install gcc python3 ninja zlib
          pip3 install meson

      - name: Set up FreeBSD
        if: matrix.freebsd
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          prepare: |
            pkg install -y python3 py39-pip ninja gcc zlib
            pip install meson

      - name: Set SDKROOT on macOS
        if: runner.os == 'macOS'
        run: echo "SDKROOT=$(xcrun --show-sdk-path)" >> $GITHUB_ENV

      - name: Build (non-FreeBSD)
        if: !matrix.freebsd
        run: |
          meson setup builddir
          meson compile -C builddir

      - name: Build (FreeBSD)
        if: matrix.freebsd
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          run: |
            meson setup builddir
            meson compile -C builddir

      - name: Rename binary
        run: |
          mv builddir/pkgrip pkgrip-${{ runner.os }}-${{ matrix.arch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pkgrip-${{ runner.os }}-${{ matrix.arch }}
          path: pkgrip-${{ runner.os }}-${{ matrix.arch }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: pkgrip-build

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          body: |
            Changelog:
              ${{ github.event.head_commit.message }}
          files: |
            ./pkgrip-build/pkgrip-Linux-x86_64/pkgrip-Linux-x86_64
            ./pkgrip-build/pkgrip-Linux-aarch64/pkgrip-Linux-aarch64
            ./pkgrip-build/pkgrip-macOS-x86_64/pkgrip-macOS-x86_64
            ./pkgrip-build/pkgrip-macOS-arm64/pkgrip-macOS-arm64
            ./pkgrip-build/pkgrip-FreeBSD-x86_64/pkgrip-FreeBSD-x86_64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
