name: Release

on:
  push:

permissions:
  contents: write
  discussions: write

jobs:
  build-and-release:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y gcc make zlib1g-dev
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew update
            brew install gcc make zlib
          fi

      - name: Set SDKROOT on macOS
        if: runner.os == 'macOS'
        run: echo "SDKROOT=$(xcrun --show-sdk-path)" >> $GITHUB_ENV

      - name: Build
        run: |
          make clean
          make all

      - name: Rename binary
        run: |
          mv pkgrip pkgrip-${{ runner.os }}-${{ runner.arch }}
