name: Release

on:
  push:

permissions:
  contents: write
  discussions: write

jobs:
  build-and-release:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up GCC on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc

      - name: Set up GCC on macOS
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install gcc

      - name: Build
        run: make

      - name: Rename binary
        run: |
          mv pkgrip pkgrip-${{ runner.os }}-${{ runner.arch }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: pkgrip-${{ runner.os }}-${{ runner.arch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
